# Generated by Django 3.1 on 2020-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('house', models.CharField(max_length=20)),
                ('rent_recieved', models.IntegerField()),
                ('account', models.CharField(max_length=30)),
            ],
        ),
    ]
