# Generated by Django 3.1 on 2020-08-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0002_ebbillmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicAccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recieved_expense', models.CharField(max_length=30)),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
