# Generated by Django 3.1 on 2020-08-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0003_publicaccount_publicaccountdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaccountdetails',
            name='recieved_expense',
        ),
        migrations.AddField(
            model_name='publicaccountdetails',
            name='expense',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publicaccountdetails',
            name='recieved',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
