# Generated by Django 3.1 on 2020-08-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0005_auto_20200828_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccountdetails',
            name='balance_history',
            field=models.FloatField(null=True),
        ),
    ]
