# Generated by Django 3.1 on 2020-08-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0006_publicaccountdetails_balance_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraneOperatorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('leave_advance', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
            ],
        ),
    ]
