# Generated by Django 3.1 on 2020-08-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0007_craneoperatordetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craneoperatordetails',
            name='balance',
            field=models.FloatField(null=True),
        ),
    ]
