# Generated by Django 3.1 on 2020-08-31 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0008_auto_20200831_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CraneOperatorDetails',
            new_name='CraneOperatorDetailsModel',
        ),
    ]
