# Generated by Django 3.1 on 2020-09-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0009_auto_20200831_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraneCompanyBillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('main_date', models.DateField()),
                ('bill_number', models.IntegerField()),
                ('sub_date', models.DateField()),
                ('hours', models.TimeField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
