# Generated by Django 3.1 on 2020-09-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0010_cranecompanybillmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGPModelSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_bill', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IGPModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tot_hours', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('seq_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dineshApp.igpmodelsequence')),
            ],
        ),
    ]
