# Generated by Django 3.1 on 2020-09-09 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0011_igpmodel_igpmodelsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraneBillMainDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('main_date', models.DateField()),
                ('bill_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CraneBillSubDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_date', models.DateField()),
                ('hours', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('main_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dineshApp.cranebillmaindate')),
            ],
        ),
        migrations.DeleteModel(
            name='CraneCompanyBillModel',
        ),
    ]
