# Generated by Django 3.1 on 2020-09-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0012_auto_20200909_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('notes', models.TextField()),
            ],
        ),
    ]
