# Generated by Django 3.1 on 2020-09-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0013_notepadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
