# Generated by Django 3.1 on 2020-09-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0014_publicaccount_bank_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicAccount',
            new_name='PrivatePublicAccount',
        ),
    ]
