# Generated by Django 3.1 on 2020-09-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0016_privateaccountdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateAccountDetails',
            new_name='PrivateAccountDetailsModel',
        ),
    ]
