# Generated by Django 3.1 on 2020-09-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0017_auto_20200912_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonBillCalculationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('bill_date', models.DateField()),
                ('bill_number', models.IntegerField()),
                ('tot_hours', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
