# Generated by Django 3.1 on 2020-09-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineshApp', '0018_commonbillcalculationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMasterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
